sudo: required
dist: trusty

language: node_js


cache:
  directories:
    - $HOME/.npm

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

script:
  - sh ./testscli.sh